### ISSUE TITLE
Now broken in Google Chrome 44.0.2403.130 (64-bit) :-( 

### ISSUE THREAD

**Issue by PhilETaylor** [HubSpot/signet#15]
This all used to work perfectly in my project (manage.myjoomla.com) - but stopped working

On testing on your live site its broken there too now - Note the missing icons and whitespace :-( 

![image 2015-08-04 at 11 08 15 pm](https://cloud.githubusercontent.com/assets/400092/9074014/c2e073ce-3afd-11e5-86c4-d98a6457df7d.png)

My browser stats: 
![screen shot 2015-08-04 at 23 08 50](https://cloud.githubusercontent.com/assets/400092/9074032/e8248a6c-3afd-11e5-9115-bf7775d62e74.png)

**Comment by adamschwartz** [comment]
Looks like Chrome now adds a wrapper `<span>` around the links in the console and applies the same inline styles to both. Since we applied a negative margin, we’re getting double the margin we want, [so I halved it](https://github.com/HubSpot/signet/commit/0a923185a40d30270aa4b87b83bff08fce2d52df#diff-d1b4b3f9be03c4eddbcab93c0224eef5R154), which seems to do have done the trick.

<img width="1284" alt="console link styling" src="https://cloud.githubusercontent.com/assets/154613/9077553/841a7bd0-3afd-11e5-8452-3d3e6568912d.png">

**Comment by PhilETaylor** [comment]
Thanks for that - its now working again on my site here:  https://local-manage.myjoomla.com/login

Dont forget to update your site though - as its still broken (after a cache refresh) at http://github.hubspot.com/signet/

**Comment by adamschwartz** [comment]
Updated, thanks.
